# Generated by Django 2.0.3 on 2018-03-23 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabs', '0005_auto_20180323_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': 'Artist', 'verbose_name_plural': 'Artists'},
        ),
        migrations.AlterModelOptions(
            name='tab',
            options={'verbose_name': 'Tab', 'verbose_name_plural': 'Tabs'},
        ),
        migrations.AddField(
            model_name='artist',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='wikipedia',
            field=models.URLField(blank=True, null=True),
        ),
    ]
